name: Build and Publish image

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v2
      - name: Build Docker Image
        run: docker build . --tag my-image-name

      - name: Publish Image
        uses: elgohr/Publish-Docker-Github/Action@main
        with:
          name: NeonHermit/github-actions
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
