on:
  push:
    branches:
      - main

name: Test Across

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.19.x, 1.18.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Lint
        run: |
          go fmt ./...
          go vet ./...

      - name: Test
        run: go test ./...
